using PipeWireSharp.Native;

namespace PipeWireSharp.Spa.Enums;

public enum SpaMediaSubType : uint
{
    Unknown = Bindings.SPA_MEDIA_SUBTYPE_unknown,
    Raw = Bindings.SPA_MEDIA_SUBTYPE_raw,
    Dsp = Bindings.SPA_MEDIA_SUBTYPE_dsp,
    Iec958 = Bindings.SPA_MEDIA_SUBTYPE_iec958,
    Dsd = Bindings.SPA_MEDIA_SUBTYPE_dsd,
    StartAudio = Bindings.SPA_MEDIA_SUBTYPE_START_Audio,
    Mp3 = Bindings.SPA_MEDIA_SUBTYPE_mp3,
    Aac = Bindings.SPA_MEDIA_SUBTYPE_aac,
    Vorbis = Bindings.SPA_MEDIA_SUBTYPE_vorbis,
    Wma = Bindings.SPA_MEDIA_SUBTYPE_wma,
    Ra = Bindings.SPA_MEDIA_SUBTYPE_ra,
    Sbc = Bindings.SPA_MEDIA_SUBTYPE_sbc,
    Adpcm = Bindings.SPA_MEDIA_SUBTYPE_adpcm,
    G723 = Bindings.SPA_MEDIA_SUBTYPE_g723,
    G726 = Bindings.SPA_MEDIA_SUBTYPE_g726,
    G729 = Bindings.SPA_MEDIA_SUBTYPE_g729,
    Amr = Bindings.SPA_MEDIA_SUBTYPE_amr,
    Gsm = Bindings.SPA_MEDIA_SUBTYPE_gsm,
    Alac = Bindings.SPA_MEDIA_SUBTYPE_alac,
    Flac = Bindings.SPA_MEDIA_SUBTYPE_flac,
    Ape = Bindings.SPA_MEDIA_SUBTYPE_ape,
    Opus = Bindings.SPA_MEDIA_SUBTYPE_opus,
    StartVideo = Bindings.SPA_MEDIA_SUBTYPE_START_Video,
    H264 = Bindings.SPA_MEDIA_SUBTYPE_h264,
    Mjpg = Bindings.SPA_MEDIA_SUBTYPE_mjpg,
    Dv = Bindings.SPA_MEDIA_SUBTYPE_dv,
    Mpegts = Bindings.SPA_MEDIA_SUBTYPE_mpegts,
    H263 = Bindings.SPA_MEDIA_SUBTYPE_h263,
    Mpeg1 = Bindings.SPA_MEDIA_SUBTYPE_mpeg1,
    Mpeg2 = Bindings.SPA_MEDIA_SUBTYPE_mpeg2,
    Mpeg4 = Bindings.SPA_MEDIA_SUBTYPE_mpeg4,
    Xvid = Bindings.SPA_MEDIA_SUBTYPE_xvid,
    Vc1 = Bindings.SPA_MEDIA_SUBTYPE_vc1,
    Vp8 = Bindings.SPA_MEDIA_SUBTYPE_vp8,
    Vp9 = Bindings.SPA_MEDIA_SUBTYPE_vp9,
    Bayer = Bindings.SPA_MEDIA_SUBTYPE_bayer,
    StartImage = Bindings.SPA_MEDIA_SUBTYPE_START_Image,
    Jpeg = Bindings.SPA_MEDIA_SUBTYPE_jpeg,
    StartBinary = Bindings.SPA_MEDIA_SUBTYPE_START_Binary,
    StartStream = Bindings.SPA_MEDIA_SUBTYPE_START_Stream,
    Midi = Bindings.SPA_MEDIA_SUBTYPE_midi,
    StartApplication = Bindings.SPA_MEDIA_SUBTYPE_START_Application,
    Control = Bindings.SPA_MEDIA_SUBTYPE_control,
}