using PipeWireSharp.Native;

namespace PipeWireSharp.Spa.Enums;

public enum SpaProperty : uint
{
    InfoStart = Bindings.SPA_PROP_INFO_START,
    InfoId = Bindings.SPA_PROP_INFO_id,
    InfoName = Bindings.SPA_PROP_INFO_name,
    InfoType = Bindings.SPA_PROP_INFO_type,
    InfoLabels = Bindings.SPA_PROP_INFO_labels,
    InfoContainer = Bindings.SPA_PROP_INFO_container,
    InfoParams = Bindings.SPA_PROP_INFO_params,
    InfoDescription = Bindings.SPA_PROP_INFO_description,
    Start = Bindings.SPA_PROP_START,
    Unknown = Bindings.SPA_PROP_unknown,
    StartDevice = Bindings.SPA_PROP_START_Device,
    Device = Bindings.SPA_PROP_device,
    DeviceName = Bindings.SPA_PROP_deviceName,
    DeviceFd = Bindings.SPA_PROP_deviceFd,
    Card = Bindings.SPA_PROP_card,
    CardName = Bindings.SPA_PROP_cardName,
    MinLatency = Bindings.SPA_PROP_minLatency,
    MaxLatency = Bindings.SPA_PROP_maxLatency,
    Periods = Bindings.SPA_PROP_periods,
    PeriodSize = Bindings.SPA_PROP_periodSize,
    PeriodEvent = Bindings.SPA_PROP_periodEvent,
    Live = Bindings.SPA_PROP_live,
    Rate = Bindings.SPA_PROP_rate,
    Quality = Bindings.SPA_PROP_quality,
    BluetoothAudioCodec = Bindings.SPA_PROP_bluetoothAudioCodec,
    BluetoothOffloadActive = Bindings.SPA_PROP_bluetoothOffloadActive,
    StartAudio = Bindings.SPA_PROP_START_Audio,
    AudioWaveType = Bindings.SPA_PROP_waveType,
    AudioFrequency = Bindings.SPA_PROP_frequency,
    AudioVolume = Bindings.SPA_PROP_volume,
    AudioMute = Bindings.SPA_PROP_mute,
    AudioPatternType = Bindings.SPA_PROP_patternType,
    AudioDitherType = Bindings.SPA_PROP_ditherType,
    AudioTruncate = Bindings.SPA_PROP_truncate,
    AudioChannelVolumes = Bindings.SPA_PROP_channelVolumes,
    AudioVolumeBase = Bindings.SPA_PROP_volumeBase,
    AudioVolumeStep = Bindings.SPA_PROP_volumeStep,
    AudioChannelMap = Bindings.SPA_PROP_channelMap,
    AudioMonitorMute = Bindings.SPA_PROP_monitorMute,
    AudioMonitorVolumes = Bindings.SPA_PROP_monitorVolumes,
    AudioLatencyOffsetNsec = Bindings.SPA_PROP_latencyOffsetNsec,
    AudioSoftMute = Bindings.SPA_PROP_softMute,
    AudioSoftVolumes = Bindings.SPA_PROP_softVolumes,
    AudioIec = Bindings.SPA_PROP_iec958Codecs,
    AudioVolumeRampSamples = Bindings.SPA_PROP_volumeRampSamples,
    AudioVolumeRampStepSamples = Bindings.SPA_PROP_volumeRampStepSamples,
    AudioVolumeRampTime = Bindings.SPA_PROP_volumeRampTime,
    AudioVolumeRampStepTime = Bindings.SPA_PROP_volumeRampStepTime,
    AudioVolumeRampScale = Bindings.SPA_PROP_volumeRampScale,
    StartVideo = Bindings.SPA_PROP_START_Video,
    VideoBrightness = Bindings.SPA_PROP_brightness,
    VideoContrast = Bindings.SPA_PROP_contrast,
    VideoSaturation = Bindings.SPA_PROP_saturation,
    VideoHue = Bindings.SPA_PROP_hue,
    VideoGamma = Bindings.SPA_PROP_gamma,
    VideoExposure = Bindings.SPA_PROP_exposure,
    VideoGain = Bindings.SPA_PROP_gain,
    VideoSharpness = Bindings.SPA_PROP_sharpness,
    StartOther = Bindings.SPA_PROP_START_Other,
    PropParams = Bindings.SPA_PROP_params,
    StartCustom = Bindings.SPA_PROP_START_CUSTOM,
}